name: Post Deployment Workflow

on:
  workflow_run:
    workflows:
      - Deploy Content to *
    types:
      - completed
      
jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Send Teams Message if failed
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: Workflow Run Failed On GitHub - ${{ github.event.workflow_run.html_url }}
          notification-color: dc3545 
  
  on-success-prepare:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Extract Variables
        id: extract-variables
        shell: pwsh
        run: |
          $workflowName="${{github.event.workflow.path}}"
          $scId=$workflowName.Substring(34,36) -replace '-',''
          echo "::set-output name=secret_name::AZURE_SENTINEL_CREDENTIALS_$scId"
          echo "::set-output name=source_control_id::$scId"

#       - name: set creds as env variable 
#         run: |
#           echo "::set-env name=CREDS::${}"
#         env: 
#           CREDS: ${{ secrets[steps.extractSecretName.outputs.name] }}
    
    outputs:
      creds_name: ${{ steps.extract-variables.outputs.secret_name }}
      source_control_id: ${{ steps.extract-variables.outputs.source_control_id }}

  on-success:
   needs: 
     - on-success-prepare
   runs-on: windows-latest
   env:
     CREDS_SECRET_NAME: ${{ needs.on-success-prepare.outputs.creds_name }}
     SOURCE_CONTROL_ID: ${{ needs.on-success-prepare.outputs.source_control_id }}
     CREDS: ${{ secrets[env.CREDS_SECRET_NAME] }}
   steps:
     - name: Login to Azure
       id: login
       uses: azure/login@v1
#        if: ${{ env.cloudEnv == 'AzureCloud' }} TODO: extract env from workflow
       with:
         creds: ${{ secrets[env.CREDS_SECRET_NAME] }}
         enable-AzPSSession: true

     - name: Checkout
       uses: actions/checkout@v1

     - name: Dispose connection
       uses: azure/powershell@v1
       with:
         azPSVersion: 'latest'
         inlineScript: |
           ${{ github.workspace }}/.github/workflows/dispose.ps1
