name: Post Deployment Workflow

on:
  workflow_run:
    workflows:
      - Deploy Content to *
    types:
      - completed
      
jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Send Teams Message if failed
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: Workflow Run Failed On GitHub - ${{ github.event.workflow_run.html_url }}
          notification-color: dc3545 
  
  on-success:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Extract Secret Name
        id: extractSecretName
        shell: pwsh
        run: |
          $workflowName="${{github.event.workflow.path}}"
          $scId=$workflowName.Substring(34,36)
          echo ::set-output name=name::"AZURE_SENTINEL_CREDENTIALS_$scId"

      - name: set creds as env variable 
        env: 
          CREDS: ${{ secrets[steps.extractSecretName.outputs.name] }}
      
      - name: Login to Azure
        id: login
        uses: azure/login@v1
#         if: ${{ env.cloudEnv == 'AzureCloud' }} TODO: extract env from workflow
        with:
          creds: ${{ env.CREDS }}
          enable-AzPSSession: true
     
      - name: Checkout
        uses: actions/checkout@v1

      - name: Dispose connection
        uses: azure/powershell@v1
        with:
          azPSVersion: 'latest'
          inlineScript: |
            ${{ github.workspace }}/.github/workflows/dispose.ps1
